# Generated by Django 3.2.8 on 2021-10-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallettransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='paystack_payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
