# Generated by Django 3.2.8 on 2021-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_wallettransaction_paystack_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('transfer', 'transfer'), ('withdraw', 'withdraw')], max_length=200, null=True),
        ),
    ]
