# Generated by Django 3.2.8 on 2021-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='recipient_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
