# Generated by Django 3.2.8 on 2021-10-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_wallet_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
